ci(actions): add version guard

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -27,6 +27,12 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+      - name: Ensure tag validity
+        run: |
+          if [ $(jq -r .version package.json) != ${GITHUB_REF/\/refs\/tags\//} ]; then
+            echo "Error: $GITHUB_REF does not match package.json version"
+            exit 1
+          fi
       - name: Setup Node.js v14
         uses: actions/setup-node@v2
         with:
@@ -35,4 +41,3 @@ jobs:
         run: npm publish --dry-run
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
